// Code generated by protoc-gen-go.
// source: tensorflow/core/framework/op_def.proto
// DO NOT EDIT!

package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Defines an operation. A NodeDef in a GraphDef specifies an Op by
// using the "op" field which should match the name of a OpDef.
type OpDef struct {
	// Op names starting with an underscore are reserved for internal use.
	// Names should be CamelCase and match the regexp "[A-Z][a-zA-Z0-9_]*".
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Description of the input(s).
	InputArg []*OpDef_ArgDef `protobuf:"bytes,2,rep,name=input_arg,json=inputArg" json:"input_arg,omitempty"`
	// Description of the output(s).
	OutputArg []*OpDef_ArgDef  `protobuf:"bytes,3,rep,name=output_arg,json=outputArg" json:"output_arg,omitempty"`
	Attr      []*OpDef_AttrDef `protobuf:"bytes,4,rep,name=attr" json:"attr,omitempty"`
	// Optional deprecation based on GraphDef versions.
	Deprecation *OpDeprecation `protobuf:"bytes,8,opt,name=deprecation" json:"deprecation,omitempty"`
	// One-line human-readable description of what the Op does.
	Summary string `protobuf:"bytes,5,opt,name=summary" json:"summary,omitempty"`
	// Additional, longer human-readable description of what the Op does.
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	// True if the operation is commutative ("op(a,b) == op(b,a)" for all inputs)
	IsCommutative bool `protobuf:"varint,18,opt,name=is_commutative,json=isCommutative" json:"is_commutative,omitempty"`
	// If is_aggregate is true, then this operation accepts N >= 2
	// inputs and produces 1 output all of the same type.  Should be
	// associative and commutative, and produce output with the same
	// shape as the input.  The optimizer may replace an aggregate op
	// taking input from multiple devices with a tree of aggregate ops
	// that aggregate locally within each device (and possibly within
	// groups of nearby devices) before communicating.
	// TODO(josh11b): Implement that optimization.
	IsAggregate bool `protobuf:"varint,16,opt,name=is_aggregate,json=isAggregate" json:"is_aggregate,omitempty"`
	// By default Ops may be moved between devices.  Stateful ops should
	// either not be moved, or should only be moved if that state can also
	// be moved (e.g. via some sort of save / restore).
	// Stateful ops are guaranteed to never be optimized away by Common
	// Subexpression Elimination (CSE).
	IsStateful bool `protobuf:"varint,17,opt,name=is_stateful,json=isStateful" json:"is_stateful,omitempty"`
	// By default, all inputs to an Op must be initialized Tensors.  Ops
	// that may initialize tensors for the first time should set this
	// field to true, to allow the Op to take an uninitialized Tensor as
	// input.
	AllowsUninitializedInput bool `protobuf:"varint,19,opt,name=allows_uninitialized_input,json=allowsUninitializedInput" json:"allows_uninitialized_input,omitempty"`
}

func (m *OpDef) Reset()                    { *m = OpDef{} }
func (m *OpDef) String() string            { return proto.CompactTextString(m) }
func (*OpDef) ProtoMessage()               {}
func (*OpDef) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0} }

func (m *OpDef) GetInputArg() []*OpDef_ArgDef {
	if m != nil {
		return m.InputArg
	}
	return nil
}

func (m *OpDef) GetOutputArg() []*OpDef_ArgDef {
	if m != nil {
		return m.OutputArg
	}
	return nil
}

func (m *OpDef) GetAttr() []*OpDef_AttrDef {
	if m != nil {
		return m.Attr
	}
	return nil
}

func (m *OpDef) GetDeprecation() *OpDeprecation {
	if m != nil {
		return m.Deprecation
	}
	return nil
}

// For describing inputs and outputs.
type OpDef_ArgDef struct {
	// Name for the input/output.  Should match the regexp "[a-z][a-z0-9_]*".
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// Human readable description.
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	// Describes the type of one or more tensors that are accepted/produced
	// by this input/output arg.  The only legal combinations are:
	// * For a single tensor: either the "type" field is set or the
	//   "type_attr" field is set to the name of an attr with type "type".
	// * For a sequence of tensors with the same type: the "number_attr"
	//   field will be set to the name of an attr with type "int", and
	//   either the "type" or "type_attr" field will be set as for
	//   single tensors.
	// * For a sequence of tensors, the "type_list_attr" field will be set
	//   to the name of an attr with type "list(type)".
	Type       DataType `protobuf:"varint,3,opt,name=type,enum=tensorflow.DataType" json:"type,omitempty"`
	TypeAttr   string   `protobuf:"bytes,4,opt,name=type_attr,json=typeAttr" json:"type_attr,omitempty"`
	NumberAttr string   `protobuf:"bytes,5,opt,name=number_attr,json=numberAttr" json:"number_attr,omitempty"`
	// If specified, attr must have type "list(type)", and none of
	// type, type_attr, and number_attr may be specified.
	TypeListAttr string `protobuf:"bytes,6,opt,name=type_list_attr,json=typeListAttr" json:"type_list_attr,omitempty"`
	// For inputs: if true, the inputs are required to be refs.
	//   By default, inputs can be either refs or non-refs.
	// For outputs: if true, outputs are refs, otherwise they are not.
	IsRef bool `protobuf:"varint,16,opt,name=is_ref,json=isRef" json:"is_ref,omitempty"`
}

func (m *OpDef_ArgDef) Reset()                    { *m = OpDef_ArgDef{} }
func (m *OpDef_ArgDef) String() string            { return proto.CompactTextString(m) }
func (*OpDef_ArgDef) ProtoMessage()               {}
func (*OpDef_ArgDef) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0, 0} }

// Description of the graph-construction-time configuration of this
// Op.  That is to say, this describes the attr fields that will
// be specified in the NodeDef.
type OpDef_AttrDef struct {
	// A descriptive name for the argument.  May be used, e.g. by the
	// Python client, as a keyword argument name, and so should match
	// the regexp "[a-z][a-z0-9_]+".
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// One of the type names from attr_value.proto ("string", "list(string)",
	// "int", etc.).
	Type string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	// A reasonable default for this attribute if the user does not supply
	// a value.  If not specified, the user must supply a value.
	DefaultValue *AttrValue `protobuf:"bytes,3,opt,name=default_value,json=defaultValue" json:"default_value,omitempty"`
	// Human-readable description.
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	// For type == "int", this is a minimum value.  For "list(___)"
	// types, this is the minimum length.
	HasMinimum bool  `protobuf:"varint,5,opt,name=has_minimum,json=hasMinimum" json:"has_minimum,omitempty"`
	Minimum    int64 `protobuf:"varint,6,opt,name=minimum" json:"minimum,omitempty"`
	// The set of allowed values.  Has type that is the "list" version
	// of the "type" field above (uses the "list" field of AttrValue).
	// If type == "type" or "list(type)" above, then the "type" field
	// of "allowed_values.list" has the set of allowed DataTypes.
	// If type == "string" or "list(string)", then the "s" field of
	// "allowed_values.list" has the set of allowed strings.
	AllowedValues *AttrValue `protobuf:"bytes,7,opt,name=allowed_values,json=allowedValues" json:"allowed_values,omitempty"`
}

func (m *OpDef_AttrDef) Reset()                    { *m = OpDef_AttrDef{} }
func (m *OpDef_AttrDef) String() string            { return proto.CompactTextString(m) }
func (*OpDef_AttrDef) ProtoMessage()               {}
func (*OpDef_AttrDef) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{0, 1} }

func (m *OpDef_AttrDef) GetDefaultValue() *AttrValue {
	if m != nil {
		return m.DefaultValue
	}
	return nil
}

func (m *OpDef_AttrDef) GetAllowedValues() *AttrValue {
	if m != nil {
		return m.AllowedValues
	}
	return nil
}

// Information about version-dependent deprecation of an op
type OpDeprecation struct {
	// First GraphDef version at which the op is disallowed.
	Version int32 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	// Explanation of why it was deprecated and what to use instead.
	Explanation string `protobuf:"bytes,2,opt,name=explanation" json:"explanation,omitempty"`
}

func (m *OpDeprecation) Reset()                    { *m = OpDeprecation{} }
func (m *OpDeprecation) String() string            { return proto.CompactTextString(m) }
func (*OpDeprecation) ProtoMessage()               {}
func (*OpDeprecation) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{1} }

// A collection of OpDefs
type OpList struct {
	Op []*OpDef `protobuf:"bytes,1,rep,name=op" json:"op,omitempty"`
}

func (m *OpList) Reset()                    { *m = OpList{} }
func (m *OpList) String() string            { return proto.CompactTextString(m) }
func (*OpList) ProtoMessage()               {}
func (*OpList) Descriptor() ([]byte, []int) { return fileDescriptor9, []int{2} }

func (m *OpList) GetOp() []*OpDef {
	if m != nil {
		return m.Op
	}
	return nil
}

func init() {
	proto.RegisterType((*OpDef)(nil), "tensorflow.OpDef")
	proto.RegisterType((*OpDef_ArgDef)(nil), "tensorflow.OpDef.ArgDef")
	proto.RegisterType((*OpDef_AttrDef)(nil), "tensorflow.OpDef.AttrDef")
	proto.RegisterType((*OpDeprecation)(nil), "tensorflow.OpDeprecation")
	proto.RegisterType((*OpList)(nil), "tensorflow.OpList")
}

func init() { proto.RegisterFile("tensorflow/core/framework/op_def.proto", fileDescriptor9) }

var fileDescriptor9 = []byte{
	// 625 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x94, 0xcb, 0x6e, 0x13, 0x31,
	0x14, 0x86, 0x35, 0xb9, 0xe7, 0x4c, 0x13, 0x51, 0x43, 0x25, 0x13, 0x16, 0x4d, 0x2b, 0x8a, 0x22,
	0x2e, 0xa9, 0x54, 0x84, 0x90, 0xa0, 0x9b, 0x96, 0x6e, 0x10, 0xa0, 0x56, 0xc3, 0x65, 0x3b, 0x72,
	0x13, 0xcf, 0xd4, 0x62, 0x66, 0x6c, 0xd9, 0x9e, 0x96, 0xf2, 0x04, 0xbc, 0x1c, 0x4f, 0xc1, 0x4b,
	0xb0, 0x44, 0x3e, 0x9e, 0xb4, 0x43, 0x93, 0xc2, 0x2a, 0xf1, 0x39, 0xdf, 0xef, 0xf1, 0xff, 0xfb,
	0x02, 0x8f, 0x2c, 0x2f, 0x8c, 0xd4, 0x49, 0x26, 0x2f, 0x76, 0x67, 0x52, 0xf3, 0xdd, 0x44, 0xb3,
	0x9c, 0x5f, 0x48, 0xfd, 0x75, 0x57, 0xaa, 0x78, 0xce, 0x93, 0xa9, 0xd2, 0xd2, 0x4a, 0x02, 0xd7,
	0xdc, 0xe8, 0xf1, 0xed, 0x1a, 0x66, 0xad, 0x8e, 0xcf, 0x59, 0x56, 0x72, 0xaf, 0x1b, 0xed, 0xdc,
	0xce, 0xda, 0x4b, 0xc5, 0x8d, 0xc7, 0xb6, 0x7f, 0x76, 0xa1, 0x7d, 0xac, 0x8e, 0x78, 0x42, 0x08,
	0xb4, 0x0a, 0x96, 0x73, 0x1a, 0x8c, 0x83, 0x49, 0x3f, 0xc2, 0xff, 0xe4, 0x05, 0xf4, 0x45, 0xa1,
	0x4a, 0x1b, 0x33, 0x9d, 0xd2, 0xc6, 0xb8, 0x39, 0x09, 0xf7, 0xe8, 0xf4, 0x7a, 0xe2, 0x29, 0x2a,
	0xa7, 0x07, 0x3a, 0x3d, 0xe2, 0x49, 0xd4, 0x43, 0xf4, 0x40, 0xa7, 0xe4, 0x25, 0x80, 0x2c, 0xed,
	0x42, 0xd7, 0xfc, 0x8f, 0xae, 0xef, 0x59, 0x27, 0x7c, 0x06, 0x2d, 0x67, 0x84, 0xb6, 0x50, 0x72,
	0x7f, 0x85, 0xc4, 0x5a, 0xed, 0x34, 0x88, 0x91, 0xd7, 0x10, 0xce, 0xb9, 0xd2, 0x7c, 0xc6, 0xac,
	0x90, 0x05, 0xed, 0x8d, 0x83, 0x55, 0xaa, 0x2b, 0x20, 0xaa, 0xd3, 0x84, 0x42, 0xd7, 0x94, 0x79,
	0xce, 0xf4, 0x25, 0x6d, 0xa3, 0xe5, 0xc5, 0x90, 0x8c, 0xdd, 0xb4, 0x66, 0xa6, 0x85, 0xc2, 0x69,
	0x3b, 0xd8, 0xad, 0x97, 0xc8, 0x0e, 0x0c, 0x85, 0x89, 0x67, 0x32, 0xcf, 0x4b, 0xcb, 0xac, 0x38,
	0xe7, 0x94, 0x8c, 0x83, 0x49, 0x2f, 0x1a, 0x08, 0xf3, 0xe6, 0xba, 0x48, 0xb6, 0x60, 0x4d, 0x98,
	0x98, 0xa5, 0xa9, 0xe6, 0x29, 0xb3, 0x9c, 0xde, 0x41, 0x28, 0x14, 0xe6, 0x60, 0x51, 0x22, 0x9b,
	0x10, 0x0a, 0x13, 0x1b, 0xcb, 0x2c, 0x4f, 0xca, 0x8c, 0xae, 0x23, 0x01, 0xc2, 0x7c, 0xac, 0x2a,
	0x64, 0x1f, 0x46, 0x2c, 0xcb, 0xe4, 0x85, 0x89, 0xcb, 0x42, 0x14, 0xc2, 0x0a, 0x96, 0x89, 0xef,
	0x7c, 0x1e, 0x63, 0xd8, 0xf4, 0x2e, 0xf2, 0xd4, 0x13, 0x9f, 0xeb, 0xc0, 0x5b, 0xd7, 0x1f, 0xfd,
	0x0a, 0xa0, 0xe3, 0x63, 0x5e, 0xb9, 0xbf, 0x37, 0x9c, 0x36, 0x96, 0x9d, 0x4e, 0xa0, 0xe5, 0x8e,
	0x0b, 0x6d, 0x8e, 0x83, 0xc9, 0x70, 0xef, 0x5e, 0x3d, 0xdb, 0x23, 0x66, 0xd9, 0xa7, 0x4b, 0xc5,
	0x23, 0x24, 0xc8, 0x03, 0xe8, 0xbb, 0xdf, 0xb8, 0xda, 0x40, 0x37, 0x53, 0xcf, 0x15, 0xdc, 0x96,
	0x39, 0x9b, 0x45, 0x99, 0x9f, 0x72, 0xed, 0xdb, 0x3e, 0x70, 0xf0, 0x25, 0x04, 0x1e, 0xc2, 0x10,
	0xd5, 0x99, 0x30, 0xd6, 0x33, 0x3e, 0xf6, 0x35, 0x57, 0x7d, 0x2f, 0x8c, 0x45, 0x6a, 0x03, 0x3a,
	0xc2, 0xc4, 0x9a, 0x27, 0x55, 0x94, 0x6d, 0x61, 0x22, 0x9e, 0x8c, 0x7e, 0x34, 0xa0, 0x5b, 0x9d,
	0x8c, 0x95, 0x36, 0x49, 0x65, 0xc2, 0xfb, 0xf3, 0xcb, 0x7d, 0x05, 0x83, 0x39, 0x4f, 0x58, 0x99,
	0x59, 0x7f, 0x6d, 0xd0, 0x61, 0xb8, 0xb7, 0x51, 0x77, 0xe8, 0xe6, 0xfc, 0xe2, 0x9a, 0xd1, 0x5a,
	0xc5, 0xe2, 0xe8, 0x66, 0x6c, 0xad, 0xe5, 0xd8, 0x36, 0x21, 0x3c, 0x63, 0x26, 0xce, 0x45, 0x21,
	0xf2, 0x32, 0x47, 0xbf, 0xbd, 0x08, 0xce, 0x98, 0xf9, 0xe0, 0x2b, 0xee, 0xf4, 0x2d, 0x9a, 0xce,
	0x68, 0x33, 0x5a, 0x0c, 0xc9, 0x3e, 0x0c, 0x71, 0x3b, 0xf9, 0xdc, 0x2f, 0xcc, 0xd0, 0xee, 0xbf,
	0x56, 0x36, 0xa8, 0x60, 0x1c, 0x99, 0xed, 0x77, 0x30, 0xf8, 0xeb, 0xcc, 0xbb, 0x0f, 0x9d, 0x73,
	0x6d, 0xdc, 0x3a, 0x5d, 0x24, 0xed, 0x68, 0x31, 0x74, 0x2e, 0xf8, 0x37, 0x95, 0xb1, 0x82, 0xd5,
	0x37, 0xbf, 0x56, 0xda, 0x7e, 0x02, 0x9d, 0x63, 0xe5, 0xc2, 0x27, 0x5b, 0xd0, 0x90, 0x8a, 0x06,
	0x78, 0x2d, 0xd7, 0x97, 0xae, 0x65, 0xd4, 0x90, 0xea, 0xf0, 0x29, 0x50, 0xa9, 0xd3, 0x7a, 0xef,
	0xea, 0xc5, 0x39, 0x0c, 0x11, 0x3b, 0x71, 0x2f, 0x8e, 0x39, 0x09, 0x7e, 0x07, 0xc1, 0x69, 0x07,
	0x9f, 0x9f, 0xe7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x73, 0x62, 0xad, 0xd8, 0x07, 0x05, 0x00,
	0x00,
}
