// Code generated by protoc-gen-go.
// source: tensorflow/core/framework/summary.proto
// DO NOT EDIT!

package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Serialization format for histogram module in
// core/lib/histogram/histogram.h
type HistogramProto struct {
	Min        float64 `protobuf:"fixed64,1,opt,name=min" json:"min,omitempty"`
	Max        float64 `protobuf:"fixed64,2,opt,name=max" json:"max,omitempty"`
	Num        float64 `protobuf:"fixed64,3,opt,name=num" json:"num,omitempty"`
	Sum        float64 `protobuf:"fixed64,4,opt,name=sum" json:"sum,omitempty"`
	SumSquares float64 `protobuf:"fixed64,5,opt,name=sum_squares,json=sumSquares" json:"sum_squares,omitempty"`
	// Parallel arrays encoding the bucket boundaries and the bucket values.
	// bucket(i) is the count for the bucket i.  The range for
	// a bucket is:
	//   i == 0:  -DBL_MAX .. bucket_limit(0)
	//   i != 0:  bucket_limit(i-1) .. bucket_limit(i)
	BucketLimit []float64 `protobuf:"fixed64,6,rep,packed,name=bucket_limit,json=bucketLimit" json:"bucket_limit,omitempty"`
	Bucket      []float64 `protobuf:"fixed64,7,rep,packed,name=bucket" json:"bucket,omitempty"`
}

func (m *HistogramProto) Reset()                    { *m = HistogramProto{} }
func (m *HistogramProto) String() string            { return proto.CompactTextString(m) }
func (*HistogramProto) ProtoMessage()               {}
func (*HistogramProto) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{0} }

// A Summary is a set of named values to be displayed by the
// visualizer.
//
// Summaries are produced regularly during training, as controlled by
// the "summary_interval_secs" attribute of the training operation.
// Summaries are also produced at the end of an evaluation.
type Summary struct {
	// Set of values for the summary.
	Value []*Summary_Value `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *Summary) Reset()                    { *m = Summary{} }
func (m *Summary) String() string            { return proto.CompactTextString(m) }
func (*Summary) ProtoMessage()               {}
func (*Summary) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1} }

func (m *Summary) GetValue() []*Summary_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

type Summary_Image struct {
	// Dimensions of the image.
	Height int32 `protobuf:"varint,1,opt,name=height" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	// Valid colorspace values are
	//   1 - grayscale
	//   2 - grayscale + alpha
	//   3 - RGB
	//   4 - RGBA
	//   5 - DIGITAL_YUV
	//   6 - BGRA
	Colorspace int32 `protobuf:"varint,3,opt,name=colorspace" json:"colorspace,omitempty"`
	// Image data in encoded format.  All image formats supported by
	// image_codec::CoderUtil can be stored here.
	EncodedImageString []byte `protobuf:"bytes,4,opt,name=encoded_image_string,json=encodedImageString,proto3" json:"encoded_image_string,omitempty"`
}

func (m *Summary_Image) Reset()                    { *m = Summary_Image{} }
func (m *Summary_Image) String() string            { return proto.CompactTextString(m) }
func (*Summary_Image) ProtoMessage()               {}
func (*Summary_Image) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1, 0} }

type Summary_Audio struct {
	// Sample rate of the audio in Hz.
	SampleRate float32 `protobuf:"fixed32,1,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	// Number of channels of audio.
	NumChannels int64 `protobuf:"varint,2,opt,name=num_channels,json=numChannels" json:"num_channels,omitempty"`
	// Length of the audio in frames (samples per channel).
	LengthFrames int64 `protobuf:"varint,3,opt,name=length_frames,json=lengthFrames" json:"length_frames,omitempty"`
	// Encoded audio data and its associated RFC 2045 content type (e.g.
	// "audio/wav").
	EncodedAudioString []byte `protobuf:"bytes,4,opt,name=encoded_audio_string,json=encodedAudioString,proto3" json:"encoded_audio_string,omitempty"`
	ContentType        string `protobuf:"bytes,5,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
}

func (m *Summary_Audio) Reset()                    { *m = Summary_Audio{} }
func (m *Summary_Audio) String() string            { return proto.CompactTextString(m) }
func (*Summary_Audio) ProtoMessage()               {}
func (*Summary_Audio) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1, 1} }

type Summary_Value struct {
	// Name of the node that output this summary; in general, the name of a
	// TensorSummary node. If the node in question has multiple outputs, then
	// a ":\d+" suffix will be appended, like "some_op:13".
	// Might not be set for legacy summaries (i.e. those not using the tensor
	// value field)
	NodeName string `protobuf:"bytes,7,opt,name=node_name,json=nodeName" json:"node_name,omitempty"`
	// Tag name for the data.  Will only be used by legacy summaries
	// (ie. those not using the tensor value field)
	// For legacy summaries, will be used as the title of the graph
	// in the visualizer.
	//
	// Tag is usually "op_name:value_name", where "op_name" itself can have
	// structure to indicate grouping.
	Tag string `protobuf:"bytes,1,opt,name=tag" json:"tag,omitempty"`
	// Value associated with the tag.
	//
	// Types that are valid to be assigned to Value:
	//	*Summary_Value_SimpleValue
	//	*Summary_Value_ObsoleteOldStyleHistogram
	//	*Summary_Value_Image
	//	*Summary_Value_Histo
	//	*Summary_Value_Audio
	//	*Summary_Value_Tensor
	Value isSummary_Value_Value `protobuf_oneof:"value"`
}

func (m *Summary_Value) Reset()                    { *m = Summary_Value{} }
func (m *Summary_Value) String() string            { return proto.CompactTextString(m) }
func (*Summary_Value) ProtoMessage()               {}
func (*Summary_Value) Descriptor() ([]byte, []int) { return fileDescriptor11, []int{1, 2} }

type isSummary_Value_Value interface {
	isSummary_Value_Value()
}

type Summary_Value_SimpleValue struct {
	SimpleValue float32 `protobuf:"fixed32,2,opt,name=simple_value,json=simpleValue,oneof"`
}
type Summary_Value_ObsoleteOldStyleHistogram struct {
	ObsoleteOldStyleHistogram []byte `protobuf:"bytes,3,opt,name=obsolete_old_style_histogram,json=obsoleteOldStyleHistogram,proto3,oneof"`
}
type Summary_Value_Image struct {
	Image *Summary_Image `protobuf:"bytes,4,opt,name=image,oneof"`
}
type Summary_Value_Histo struct {
	Histo *HistogramProto `protobuf:"bytes,5,opt,name=histo,oneof"`
}
type Summary_Value_Audio struct {
	Audio *Summary_Audio `protobuf:"bytes,6,opt,name=audio,oneof"`
}
type Summary_Value_Tensor struct {
	Tensor *TensorProto `protobuf:"bytes,8,opt,name=tensor,oneof"`
}

func (*Summary_Value_SimpleValue) isSummary_Value_Value()               {}
func (*Summary_Value_ObsoleteOldStyleHistogram) isSummary_Value_Value() {}
func (*Summary_Value_Image) isSummary_Value_Value()                     {}
func (*Summary_Value_Histo) isSummary_Value_Value()                     {}
func (*Summary_Value_Audio) isSummary_Value_Value()                     {}
func (*Summary_Value_Tensor) isSummary_Value_Value()                    {}

func (m *Summary_Value) GetValue() isSummary_Value_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Summary_Value) GetSimpleValue() float32 {
	if x, ok := m.GetValue().(*Summary_Value_SimpleValue); ok {
		return x.SimpleValue
	}
	return 0
}

func (m *Summary_Value) GetObsoleteOldStyleHistogram() []byte {
	if x, ok := m.GetValue().(*Summary_Value_ObsoleteOldStyleHistogram); ok {
		return x.ObsoleteOldStyleHistogram
	}
	return nil
}

func (m *Summary_Value) GetImage() *Summary_Image {
	if x, ok := m.GetValue().(*Summary_Value_Image); ok {
		return x.Image
	}
	return nil
}

func (m *Summary_Value) GetHisto() *HistogramProto {
	if x, ok := m.GetValue().(*Summary_Value_Histo); ok {
		return x.Histo
	}
	return nil
}

func (m *Summary_Value) GetAudio() *Summary_Audio {
	if x, ok := m.GetValue().(*Summary_Value_Audio); ok {
		return x.Audio
	}
	return nil
}

func (m *Summary_Value) GetTensor() *TensorProto {
	if x, ok := m.GetValue().(*Summary_Value_Tensor); ok {
		return x.Tensor
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Summary_Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Summary_Value_OneofMarshaler, _Summary_Value_OneofUnmarshaler, _Summary_Value_OneofSizer, []interface{}{
		(*Summary_Value_SimpleValue)(nil),
		(*Summary_Value_ObsoleteOldStyleHistogram)(nil),
		(*Summary_Value_Image)(nil),
		(*Summary_Value_Histo)(nil),
		(*Summary_Value_Audio)(nil),
		(*Summary_Value_Tensor)(nil),
	}
}

func _Summary_Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Summary_Value)
	// value
	switch x := m.Value.(type) {
	case *Summary_Value_SimpleValue:
		b.EncodeVarint(2<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.SimpleValue)))
	case *Summary_Value_ObsoleteOldStyleHistogram:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.ObsoleteOldStyleHistogram)
	case *Summary_Value_Image:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Image); err != nil {
			return err
		}
	case *Summary_Value_Histo:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Histo); err != nil {
			return err
		}
	case *Summary_Value_Audio:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Audio); err != nil {
			return err
		}
	case *Summary_Value_Tensor:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Tensor); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Summary_Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Summary_Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Summary_Value)
	switch tag {
	case 2: // value.simple_value
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &Summary_Value_SimpleValue{math.Float32frombits(uint32(x))}
		return true, err
	case 3: // value.obsolete_old_style_histogram
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.Value = &Summary_Value_ObsoleteOldStyleHistogram{x}
		return true, err
	case 4: // value.image
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Summary_Image)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Image{msg}
		return true, err
	case 5: // value.histo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HistogramProto)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Histo{msg}
		return true, err
	case 6: // value.audio
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Summary_Audio)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Audio{msg}
		return true, err
	case 8: // value.tensor
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(TensorProto)
		err := b.DecodeMessage(msg)
		m.Value = &Summary_Value_Tensor{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Summary_Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Summary_Value)
	// value
	switch x := m.Value.(type) {
	case *Summary_Value_SimpleValue:
		n += proto.SizeVarint(2<<3 | proto.WireFixed32)
		n += 4
	case *Summary_Value_ObsoleteOldStyleHistogram:
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.ObsoleteOldStyleHistogram)))
		n += len(x.ObsoleteOldStyleHistogram)
	case *Summary_Value_Image:
		s := proto.Size(x.Image)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Histo:
		s := proto.Size(x.Histo)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Audio:
		s := proto.Size(x.Audio)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Summary_Value_Tensor:
		s := proto.Size(x.Tensor)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*HistogramProto)(nil), "tensorflow.HistogramProto")
	proto.RegisterType((*Summary)(nil), "tensorflow.Summary")
	proto.RegisterType((*Summary_Image)(nil), "tensorflow.Summary.Image")
	proto.RegisterType((*Summary_Audio)(nil), "tensorflow.Summary.Audio")
	proto.RegisterType((*Summary_Value)(nil), "tensorflow.Summary.Value")
}

func init() { proto.RegisterFile("tensorflow/core/framework/summary.proto", fileDescriptor11) }

var fileDescriptor11 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x93, 0xcf, 0x6e, 0x13, 0x3b,
	0x14, 0xc6, 0x3b, 0xc9, 0x9d, 0x49, 0x7b, 0x26, 0xbd, 0xaa, 0xac, 0xea, 0xde, 0x69, 0x40, 0x50,
	0x5a, 0x01, 0x5d, 0x25, 0xb4, 0x3c, 0x41, 0x83, 0x84, 0x82, 0x84, 0xa0, 0x72, 0x2a, 0xb6, 0x23,
	0x77, 0xe6, 0x74, 0x32, 0xea, 0xd8, 0x0e, 0x63, 0x9b, 0x36, 0x6b, 0x16, 0xbc, 0x14, 0x5b, 0xde,
	0x88, 0x05, 0x4b, 0xe4, 0xe3, 0x69, 0x1b, 0x24, 0xba, 0xb3, 0x7f, 0xfe, 0x3e, 0x9f, 0x3f, 0x3e,
	0x86, 0x97, 0x16, 0x95, 0xd1, 0xed, 0x65, 0xa3, 0xaf, 0x27, 0x85, 0x6e, 0x71, 0x72, 0xd9, 0x0a,
	0x89, 0xd7, 0xba, 0xbd, 0x9a, 0x18, 0x27, 0xa5, 0x68, 0x57, 0xe3, 0x65, 0xab, 0xad, 0x66, 0x70,
	0x2f, 0x1c, 0xbd, 0x78, 0xd8, 0x14, 0x4e, 0x82, 0xe7, 0xe0, 0x7b, 0x04, 0xff, 0xce, 0x6a, 0x63,
	0x75, 0xd5, 0x0a, 0x79, 0x46, 0xd7, 0xec, 0x40, 0x5f, 0xd6, 0x2a, 0x8b, 0xf6, 0xa3, 0xa3, 0x88,
	0xfb, 0x25, 0x11, 0x71, 0x93, 0xf5, 0x3a, 0x22, 0x6e, 0x3c, 0x51, 0x4e, 0x66, 0xfd, 0x40, 0x94,
	0x93, 0x9e, 0x18, 0x27, 0xb3, 0x7f, 0x02, 0x31, 0x4e, 0xb2, 0xa7, 0x90, 0x1a, 0x27, 0x73, 0xf3,
	0xd9, 0x89, 0x16, 0x4d, 0x16, 0xd3, 0x09, 0x18, 0x27, 0xe7, 0x81, 0xb0, 0xe7, 0x30, 0xbc, 0x70,
	0xc5, 0x15, 0xda, 0xbc, 0xa9, 0x65, 0x6d, 0xb3, 0x64, 0xbf, 0x7f, 0x14, 0x4d, 0x7b, 0x3b, 0x11,
	0x4f, 0x03, 0x7f, 0xef, 0x31, 0x1b, 0x41, 0x12, 0xb6, 0xd9, 0xe0, 0x4e, 0xd0, 0x91, 0x83, 0xaf,
	0x09, 0x0c, 0xe6, 0xa1, 0x09, 0x6c, 0x02, 0xf1, 0x17, 0xd1, 0x38, 0xcc, 0xa2, 0xfd, 0xfe, 0x51,
	0x7a, 0xb2, 0x37, 0xbe, 0x6f, 0xc1, 0xb8, 0xd3, 0x8c, 0x3f, 0x79, 0x01, 0x0f, 0xba, 0xd1, 0xb7,
	0x08, 0xe2, 0x77, 0x52, 0x54, 0xc8, 0xfe, 0x83, 0x64, 0x81, 0x75, 0xb5, 0xb0, 0x54, 0x75, 0xcc,
	0xbb, 0x1d, 0xdb, 0x85, 0xf8, 0xba, 0x2e, 0xed, 0x82, 0x4a, 0x8f, 0x79, 0xd8, 0xb0, 0x27, 0x00,
	0x85, 0x6e, 0x74, 0x6b, 0x96, 0xa2, 0x40, 0xea, 0x41, 0xcc, 0xd7, 0x08, 0x7b, 0x05, 0xbb, 0xa8,
	0x0a, 0x5d, 0x62, 0x99, 0xd7, 0xfe, 0xfa, 0xdc, 0xd8, 0xb6, 0x56, 0x15, 0xf5, 0x66, 0xc8, 0x59,
	0x77, 0x46, 0x91, 0xe7, 0x74, 0x32, 0xfa, 0x11, 0x41, 0x7c, 0xea, 0xca, 0x5a, 0x53, 0xd3, 0x84,
	0x5c, 0x36, 0x98, 0xb7, 0xc2, 0x22, 0xa5, 0xd3, 0xe3, 0x10, 0x10, 0x17, 0x16, 0xd9, 0x33, 0x18,
	0x2a, 0x27, 0xf3, 0x62, 0x21, 0x94, 0xc2, 0xc6, 0x50, 0x66, 0x7d, 0x9e, 0x2a, 0x27, 0xdf, 0x74,
	0x88, 0x1d, 0xc2, 0x76, 0x83, 0xaa, 0xb2, 0x8b, 0x9c, 0x1e, 0xdd, 0x50, 0x8a, 0x7d, 0x3e, 0x0c,
	0xf0, 0x2d, 0xb1, 0xf5, 0x24, 0x85, 0x8f, 0xfc, 0xf7, 0x24, 0x29, 0xa9, 0x90, 0xa4, 0x8f, 0x5c,
	0x68, 0x65, 0x51, 0xd9, 0xdc, 0xae, 0x96, 0x48, 0x0f, 0xba, 0xc5, 0xd3, 0x8e, 0x9d, 0xaf, 0x96,
	0x38, 0xfa, 0xd9, 0x83, 0x98, 0x5a, 0xcc, 0x1e, 0xc1, 0x96, 0xd2, 0x25, 0xe6, 0x4a, 0x48, 0xcc,
	0x06, 0xa4, 0xdc, 0xf4, 0xe0, 0x83, 0x90, 0xe8, 0x67, 0xc5, 0x8a, 0x8a, 0x8a, 0xdb, 0xe2, 0x7e,
	0xc9, 0x0e, 0x61, 0x68, 0x6a, 0x2a, 0x3b, 0x3c, 0xa1, 0xaf, 0xaa, 0x37, 0xdb, 0xe0, 0x69, 0xa0,
	0xe1, 0xce, 0x53, 0x78, 0xac, 0x2f, 0x8c, 0x6e, 0xd0, 0x62, 0xae, 0x9b, 0x32, 0x37, 0x76, 0xd5,
	0x60, 0xbe, 0xb8, 0x9d, 0x5e, 0x2a, 0x73, 0x38, 0xdb, 0xe0, 0x7b, 0xb7, 0xaa, 0x8f, 0x4d, 0x39,
	0xf7, 0x9a, 0xbb, 0x01, 0x67, 0xc7, 0x10, 0xd3, 0x93, 0x50, 0x99, 0x0f, 0xcc, 0x08, 0x3d, 0xcc,
	0x6c, 0x83, 0x07, 0x25, 0x3b, 0x81, 0x98, 0x42, 0x50, 0xbd, 0xe9, 0xc9, 0x68, 0xdd, 0xf2, 0xe7,
	0xcf, 0xf1, 0x1e, 0x92, 0xfa, 0x30, 0xd4, 0xd4, 0x2c, 0x79, 0x38, 0x0c, 0xb5, 0xd6, 0x5b, 0x48,
	0xc9, 0x8e, 0x21, 0x09, 0xa2, 0x6c, 0x93, 0x3c, 0xff, 0xaf, 0x7b, 0xce, 0x69, 0x79, 0x1b, 0xa4,
	0x13, 0x4e, 0x07, 0xdd, 0xc0, 0x4f, 0xc7, 0x90, 0xe9, 0xb6, 0x5a, 0x37, 0xdc, 0xfd, 0xf6, 0xe9,
	0x76, 0x17, 0x8f, 0xcc, 0xe6, 0x2c, 0xfa, 0x15, 0x45, 0x17, 0x09, 0xfd, 0xfd, 0xd7, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0xf2, 0x04, 0xae, 0x21, 0x5a, 0x04, 0x00, 0x00,
}
